●この章について +
食物・模擬団体が原材料・商品の購入に使用する「食物仕入金」について説明します。


第71期記念祭までは、学年団体のみが実施できる「食物団体」と、全団体が実施できる「模擬団体」がありました。食物団体は、調理室で調理を行った食品を販売し、模擬団体では購入した食品をそのまま販売していました。しかし、COVID-19の影響により昨年度は模擬団体のみの実施となりました。


=== 食物仕入金について

食物仕入金とは、食物・模擬団体が販売する食品の購入にあたって、自治会費から貸し出すお金のことです。実際に配布するのは、

(商品の原価) × (購入個数) + 手数料 + 配送料

を1,000円単位で切り上げた金額です。また、お金は、配布金と同じように、担当の先生に直接お渡しします。借りた食物仕入金は、返済の義務があります。食品を売れ残りなく販売できるようにしましょう。

==== 事前準備


===== 仕入金の配布
会計班から、担当の先生へお金をお渡しします。記念祭の数日前に配布する予定です。


===== 買い出し
お金が配布された時点から商品の購入が可能となります。以下の注意事項を守ってください。

* 代金引換（商品を受け取る時にお金を支払うこと）は禁止 +
  記念祭前日までにお店との交渉を行い、会計を済ませておいてください。
* 購入時は、業者による配送によらず、自分たちで受け取りに行くようにしてください
* 書類の保存
  代金を支払って発生したレシート、証明書等の書類は必ず精算会まで保存し、レシート添付ｌに貼り付けて管理してください。

===== 販売個数・単価の決定
食物模擬の第一次企画書と第二次企画書に記入した情報をもとに、食品個数を決定します。売値は、以下のルールに従い、自動的に決まります。

* 50円単位であること
* 原価を超えていること
* 最も安い金額であること

例えば、原価89円の商品は100円、原価149円の商品は150円、原価151円の商品は200円で販売することになります。


===== お釣りの用意

食物販売時に必要になるお釣りは、各団体で用意していただきます。詳しい説明は、後日お伝えします。お釣りについての注意事項は<<当日の流れ>>の「販売」の項目を参照してください。


===== 食券とチェックシート
食券は各団体で作成してください。詳しい説明は後日行います。チェックシートは幹部が作成します。当日の流れは、次項で説明します。

==== 当日の流れ

以下の流れです。

===== 食品搬入(調理)

会計班から説明することは特にありません。

===== 販売

食品を販売するときは、ミスが起きないように注意してください。売上金が不足した場合、団体に負担していただくことになります。(利益による補填はできません) +
販売の流れは以下の通りです。

. お客さんからお金をもらい、それと引き換えに *食券* を渡す。
  「食券を買う」というイメージです。
. 1と別の人が、食券に書かれている番号のチェックシートにしるしをつけたうえで、商品を手渡す。

===== 集計

食品が完売したら、すぐに幹部に連絡をしてください。幹部から支持のあったタイミングで、集計作業を行う教室に来てもらいます。


===== お釣りの返却

[IMPORTANT]
.TODO
====
食物模擬店班が食模Bookを作るらしいので、内容をすり合わせる。
====
